### PR TITLE
chore: upadted and fixed plan.md

### PR DESCRIPTION
**Pull request by EnokiUN**

### CODE REVIEW

**Review by ooliver1 — CHANGES_REQUESTED** [review]
upadted

**Review by ooliver1 — APPROVED** [review]
What if we

**Comment by EnokiUN** [comment]
close our eyes?

will it almost feel like nothing changed at all

**Comment by ooliver1** [comment]
yeah because this is still named `upadted`

**Comment by ooliver1** [comment]
https://canary.discord.com/channels/980412957060137001/1011621831335235625/1015686262226694215

**Comment by ooliver1** [comment]
upadted

**Comment by Chromosomologist** [comment]
upadted

**Comment by teaishealthy** [comment]
LGTM

**Review by ooliver1 — COMMENTED** [review]
DNLGTM

**Comment by Chromosomologist** [comment]
D4M

**Comment by teaishealthy** [comment]
So they say
Dance for me, dance for me, dance for me, oh, oh, oh
I've never seen anybody do the things you do before
They say move for me, move for me, move for me, ay, ay, ay
And when you're done I'll make you do it all again

**Comment by toolifelesstocode** [comment]
I wanna just dance, but he took me home instead
Uh-oh, there was a monster in my bed

**Pull request merged**
