### PR TITLE
feat: add eludris sex

### PR DESCRIPTION
**Pull request by EnokiUN**
## Description

This PR adds sex to Eludris, simple as that really.

## This is a **Code Change**

- [x] Docs have been updated to reflect these changes if necessary.
- [x] Changes have been tested.

### CODE REVIEW

**Comment by thesadru** [comment]
image

**Comment by Marcovdt68** [comment]
LGTM :+1:

**Review by GreenArron — APPROVED** [review]
yup nothing wrong here officer

**Review by ooliver1 — APPROVED** [review]
Uwooh :sob:

**Review by alvaro-sch — APPROVED** [review]
Saturday :call_me_hand:

**Review by Chromosomologist — CHANGES_REQUESTED** [review]
this is bad for your bones, please stop

**Comment by thesadru** [comment]
wtf enoki, keep yourself safe

**Review by Lulalaby — APPROVED** [review]
Rawr

**Comment by thesadru** [comment]
LGTM 👍

**Comment by sudo-ellipsis** [comment]
LGTM 🔥🔥🔥

**Pull request closed without merging**
