### PR TITLE
feat(cli): add a `--next` flag to the `deploy` command

### LINKED ISSUE #42: Add `--next` flag to CLI
### What would you like to be added?

A `--next` flag to the `eludris` CLI

### Why?

So that using the CLI with development/edge instances is possible.

### Examples

_No response_

### PR DESCRIPTION
**Pull request by EnokiUN**
## Description

Adds a `--next` flag to the `deploy` command which allows users to copy the files on the `next` branch when first deploying their instance.

closes #42 

## This is a **Code Change**

- [ ] ~~Docs have been updated to reflect these changes if necessary.~~ refer to #37
- [x] Changes have been tested.

### CODE REVIEW

**Comment by EnokiUN** [comment]
@Marcovdt68

**Comment by Marcovdt68** [comment]
pog

**Review by Marcovdt68 — APPROVED** [review]
LGTM  :+1:

**Review by ooliver1 — APPROVED** [review]

**Review by Chromosomologist — APPROVED** [review]
long gone trees mate

**Pull request merged**
