### PR TITLE
feat: move migration handling from Effis over to Oprish

### PR DESCRIPTION
**Pull request by ceiliaa**
## Description

This pull request moves the handling of database migrations from Effis to Oprish as per [this message](https://discord.com/channels/980412957060137001/980412957794136087/1110832622281703504).

Additionally, migration logic has been moved into a [rocket fairing](https://rocket.rs/v0.5-rc/guide/fairings/) since before a pool would be created and would persist for the entire lifetime of Effis.

## This is a **Code Change**

- [x] Docs have been updated to reflect these changes if necessary.
- [x] Changes have been tested.

### CODE REVIEW

**Review by ooliver1 — APPROVED** [review]

**Review by EnokiUN — APPROVED** [review]
LGATOMAGUMAhhh hmm hmmm use the uhh LGTM gif of course uhhhh hmmm idk

**Comment by Lulalaby** [comment]
> LGATOMAGUMAhhh hmm hmmm use the uhh LGTM gif of course uhhhh hmmm idk

lgtm

**Comment by EnokiUN** [comment]
> > LGATOMAGUMAhhh hmm hmmm use the uhh LGTM gif of course uhhhh hmmm idk
> 
> lgtm

the gif in question:



also review #69 (even though it's closed yes)

**Comment by Lulalaby** [comment]
Ahh

**Pull request merged**
